---
# tasks file for diffie-hellman

- name: Install diffie-hellman packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ diffie_hellman_packages }}"
    - "{{ diffie_hellman_additional_packages }}"
  tags:
    - package
    - diffie-hellman

- name: Generating Diffie-hellman pems
  shell: "openssl dhparam -out /etc/ssl/dh_{{ item }}.pem -2 {{ item }}"
  args:
    creates: "/etc/ssl/dh_{{ item }}.pem"
  with_items:
    - "{{ diffie_hellman_strength }}"
  tags:
    - config
    - diffie-hellman
    - skip_ansible_lint
