---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: diffie-hellman-ubuntu-1804
    image: brandfrisch/ubuntu-18.04:latest
    privileged: True
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  options:
    D: True
  lint:
    name: ansible-lint
    options:
      R: true
      r: ./node_modules/ansible-lint-rules/rules
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
